base_path = "D:/netkeiba/csv_data/"
horse_csv = base_path + "horse_new.csv"
race_csv = base_path + "race_new.csv"
payback_csv = base_path + "payback_new.csv"
condition_csv = base_path + "condition.csv"
yoso_csv = base_path + "yoso.csv"
